# Please Rename this file to config.yml
flask:
    port: 5000 # Int
mongodb:
    path: "" # String
    username: "" # String
    password: "" # String
    db_name: "" # String
    article_db: "" # String
    keyword_db: "" # String
    keyword_record_db: "" # String
    injection_db: "" # String
    log_db: "" # String
search_filter:
    result_limit_max: 20 # Int
    tf_score_min: 0.01 # Float
    sbert_article_distence_min: 0.75 # Float
    weight_of_vector:
        original: 1 # Int
        injection: 3 # Int
milvus:
    path: "localhost" # String
    port: 19530 # Int
    db_name: "default" # String
    search_config:
        basic:
            index_type: "FLAT" # String
            metric_type: "IP" # String
        article:
            collection_name: "" # String
            index_type: "FLAT" # String
            metric_type: "IP" # String
            article_filter: 5 # Int
        keyword:
            collection_name: "" # String
            index_type: "FLAT" # String
            metric_type: "L2" # String
rabbitMQ:
    host: "localhost" # String
    port: 5672 # Int
    username: "" # String
    password: "" # String
trello:
    api_key: "" # String
    token: "" # String
    request_limit: 20 # Int
ai_core:
    anthropic: "" # String
    # anthropic_api_key
    open_ai: "" # String
    # openai_api_key